### PR TITLE
Added sitemap for SEO

### PR DESCRIPTION
**Pull request by juanfdiaz98**
Tested on my fork successfully

### CODE REVIEW

**Comment by dmcwo** [comment]
Interesting idea! Is the sitemap dynamically generated?

**Comment by juanfdiaz98** [comment]
No, it has to be edited whenever paths are added.

**Comment by dmcwo** [comment]
Hmmm.... Do you happen to know if there is a way to get it to generate dynamically based on site updates?

**Comment by juanfdiaz98** [comment]
There isn't really a way but there's a way to generate one automatically and replace it easily.

**Pull request closed without merging**
